const recipes = [
  {
    id: 1,
    name: "Spaghetti Carbonara",
    img: "https://1.bp.blogspot.com/-y2Faj9FLuv8/Vr_CYPb_6VI/AAAAAAAAA_w/a6erEsz01VQ/s1600/SFS_spaghetti_carbonara_CLR-3.jpg",
    cuisine: "Italian",
    ingredients: [
      "spaghetti",
      "eggs",
      "bacon",
      "Parmesan cheese",
      "black pepper",
    ],
    instructions: [
      "Cook spaghetti according to package instructions.",
      "Fry bacon until crispy, then set aside.",
      "In a bowl, whisk eggs, cheese, and pepper.",
      "Mix cooked spaghetti with egg mixture, then add bacon.",
      "Serve hot and enjoy!",
    ],
    nutritional_information: {
      calories: 450,
      fat: 20,
      carbohydrates: 50,
      protein: 15,
    },
  },
  {
    id: 2,
    name: "Chicken Tacos",
    img: "https://www.cookingclassy.com/wp-content/uploads/2017/12/oven-roasted-chicken-tacos-7.jpg",
    cuisine: "Mexican",
    ingredients: [
      "chicken breasts",
      "tortillas",
      "avocado",
      "tomatoes",
      "lettuce",
      "sour cream",
    ],
    instructions: [
      "Grill chicken until cooked through, then slice into strips.",
      "Warm tortillas on a skillet.",
      "Fill tortillas with chicken, avocado, tomatoes, lettuce, and sour cream.",
      "Fold tortillas and serve immediately.",
    ],
    nutritional_information: {
      calories: 350,
      fat: 15,
      carbohydrates: 30,
      protein: 25,
    },
  },
  {
    id: 3,
    name: "Pad Thai",
    img: "https://itsallgoodvegan.com/wp-content/uploads/2020/02/img_2841.jpg",
    cuisine: "Thai",
    ingredients: [
      "rice noodles",
      "chicken or tofu",
      "bean sprouts",
      "peanuts",
      "green onions",
      "eggs",
      "garlic",
      "soy sauce",
      "fish sauce",
      "lime",
      "sugar",
      "vegetable oil",
    ],
    instructions: [
      "Soak rice noodles in warm water until softened, then drain.",
      "In a wok or large skillet, heat oil over medium heat. Add garlic and stir-fry until fragrant.",
      "Add chicken or tofu and cook until browned.",
      "Push ingredients to one side of the wok and crack eggs into the empty space. Scramble until cooked.",
      "Add drained noodles, soy sauce, fish sauce, and sugar. Stir-fry until noodles are tender.",
      "Stir in bean sprouts, green onions, and peanuts. Cook for another minute.",
      "Remove from heat, squeeze lime juice over the top, and serve hot.",
    ],
    nutritional_information: {
      calories: 400,
      fat: 12,
      carbohydrates: 55,
      protein: 20,
    },
  },
  {
    id: 4,
    name: "Classic Beef Burger",
    img: "https://www.appetitemag.co.uk/wp-content/uploads/2017/09/ButcherBurger.jpg",
    cuisine: "American",
    ingredients: [
      "ground beef",
      "burger buns",
      "lettuce",
      "tomato",
      "onion",
      "cheese slices",
      "ketchup",
      "mustard",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Preheat grill or skillet to medium-high heat.",
      "Season ground beef with salt and pepper, then shape into patties.",
      "Grill or cook patties until desired doneness, typically 4-5 minutes per side for medium.",
      "Toast burger buns on the grill until lightly browned.",
      "Assemble burgers with lettuce, tomato, onion, cheese, ketchup, and mustard.",
      "Serve hot with your favorite sides.",
    ],
    nutritional_information: {
      calories: 550,
      fat: 30,
      carbohydrates: 30,
      protein: 40,
    },
  },
  {
    id: 5,
    name: "Vegetable Stir-Fry",
    img: "https://therecipecritic.com/wp-content/uploads/2019/08/vegetable_stir_fry3.jpg",
    cuisine: "Asian",
    ingredients: [
      "mixed vegetables (bell peppers, broccoli, carrots, snow peas, mushrooms, etc.)",
      "tofu or chicken",
      "soy sauce",
      "sesame oil",
      "garlic",
      "ginger",
      "cornstarch",
      "vegetable oil",
      "rice (optional)",
    ],
    instructions: [
      "Prepare rice according to package instructions if using.",
      "In a small bowl, mix soy sauce, sesame oil, garlic, ginger, and cornstarch to make the sauce.",
      "Heat vegetable oil in a large skillet or wok over medium-high heat.",
      "Add tofu or chicken and cook until browned.",
      "Add mixed vegetables and stir-fry until tender-crisp.",
      "Pour sauce over the vegetables and tofu/chicken. Cook until sauce thickens.",
      "Serve hot over rice or enjoy as is.",
    ],
    nutritional_information: {
      calories: 300,
      fat: 10,
      carbohydrates: 25,
      protein: 20,
    },
  },
  {
    id: 6,
    name: "https://thebusybaker.ca/wp-content/uploads/2018/03/easy-mushroom-risotto-fbigBEST.jpg",
    img: "",
    cuisine: "Italian",
    ingredients: [
      "Arborio rice",
      "mushrooms (porcini, cremini, or your choice)",
      "onion",
      "garlic",
      "vegetable broth",
      "white wine",
      "butter",
      "Parmesan cheese",
      "olive oil",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Heat olive oil and butter in a large skillet over medium heat.",
      "Add chopped onion and cook until translucent, then add minced garlic and cook for another minute.",
      "Add Arborio rice and stir until coated with oil and slightly toasted.",
      "Pour in white wine and stir until absorbed.",
      "Begin adding vegetable broth, one ladleful at a time, stirring frequently and allowing each addition to be absorbed before adding more.",
      "After about 15-20 minutes, add sliced mushrooms to the risotto and continue adding broth until rice is creamy and tender.",
      "Stir in grated Parmesan cheese, salt, and black pepper.",
      "Serve hot, garnished with additional Parmesan if desired.",
    ],
    nutritional_information: {
      calories: 380,
      fat: 12,
      carbohydrates: 50,
      protein: 15,
    },
  },
  {
    id: 7,
    name: "Grilled Salmon with Asparagus",
    img: "https://realfood.tesco.com/media/images/112792-Pave-Grilled-Salmon-Asparagus-HERO-eed8917e-e7ea-4334-88d5-505494931f3d-0-472x310.jpg",
    cuisine: "Seafood",
    ingredients: [
      "salmon fillets",
      "asparagus spears",
      "lemon",
      "olive oil",
      "garlic",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "Rub salmon fillets with olive oil and season with salt, pepper, and minced garlic.",
      "Toss asparagus spears with olive oil, salt, and pepper.",
      "Grill salmon for 4-5 minutes per side or until desired doneness.",
      "Grill asparagus for 3-4 minutes, turning occasionally, until tender-crisp.",
      "Serve salmon and asparagus hot with lemon wedges.",
    ],
    nutritional_information: {
      calories: 320,
      fat: 20,
      carbohydrates: 8,
      protein: 30,
    },
  },
  {
    id: 8,
    name: "Greek Salad",
    img: "https://www.thechunkychef.com/wp-content/uploads/2021/07/Greek-Salad-Recipe-recipe-card.jpg",
    cuisine: "Greek",
    ingredients: [
      "tomatoes",
      "cucumbers",
      "red onion",
      "Kalamata olives",
      "feta cheese",
      "extra virgin olive oil",
      "red wine vinegar",
      "dried oregano",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Chop tomatoes, cucumbers, and red onion into bite-sized pieces.",
      "Combine chopped vegetables in a large bowl.",
      "Add Kalamata olives and crumbled feta cheese to the bowl.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper to make the dressing.",
      "Pour dressing over the salad and toss gently to coat.",
      "Serve immediately or refrigerate until ready to serve.",
    ],
    nutritional_information: {
      calories: 200,
      fat: 15,
      carbohydrates: 10,
      protein: 5,
    },
  },
  {
    id: 9,
    name: "Japanese Miso Soup",
    img: "https://www.thespruceeats.com/thmb/gnPC74NYLvdsSDbRGwwbRWoAV28=/4494x3000/filters:no_upscale():max_bytes(150000):strip_icc()/basic-miso-soup-3377886_09-5b3f7fb6c9e77c00378bf68f.jpg",
    cuisine: "Japanese",
    ingredients: [
      "dashi stock",
      "miso paste",
      "tofu",
      "green onions",
      "seaweed (nori)",
      "shiitake mushrooms (optional)",
    ],
    instructions: [
      "Bring dashi stock to a simmer in a pot.",
      "Add miso paste to the pot and stir until dissolved.",
      "Add cubed tofu and sliced mushrooms to the soup and simmer for a few minutes.",
      "Thinly slice green onions and add to the soup.",
      "Tear nori into small pieces and add to the soup just before serving.",
      "Serve hot as a starter or alongside a Japanese meal.",
    ],
    nutritional_information: {
      calories: 100,
      fat: 5,
      carbohydrates: 10,
      protein: 5,
    },
  },
  {
    id: 10,
    name: "Vegetarian Chili",
    img: "https://media1.popsugar-assets.com/files/thumbor/CWK9XtJMGqZv7zGN3qM1HtQRNkk/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/09/09/907/n/1922195/bc656b7b1f7935ae_vegetarian-chili.jpg",
    cuisine: "Mexican",
    ingredients: [
      "black beans",
      "kidney beans",
      "bell peppers",
      "onion",
      "garlic",
      "diced tomatoes",
      "corn",
      "chili powder",
      "cumin",
      "paprika",
      "vegetable broth",
      "salt",
      "black pepper",
    ],
    instructions: [
      "In a large pot, heat olive oil over medium heat.",
      "Add chopped onion and bell peppers, and cook until softened.",
      "Add minced garlic, chili powder, cumin, and paprika, and cook until fragrant.",
      "Add diced tomatoes, black beans, kidney beans, corn, and vegetable broth to the pot.",
      "Season with salt and pepper to taste.",
      "Simmer the chili for 20-30 minutes, stirring occasionally, until flavors are well combined.",
      "Serve hot, optionally garnished with shredded cheese, sour cream, and chopped cilantro.",
    ],
    nutritional_information: {
      calories: 250,
      fat: 5,
      carbohydrates: 40,
      protein: 10,
    },
  },
  {
    id: 11,
    name: "Lemon Herb Roast Chicken",
    img: "https://ohsweetbasil.com/wp-content/uploads/easy-lemon-garlic-herb-roasted-chicken-recipe-2.jpg",
    cuisine: "International",
    ingredients: [
      "whole chicken",
      "lemon",
      "garlic",
      "fresh herbs (rosemary, thyme, parsley)",
      "olive oil",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Rinse the chicken inside and out, then pat dry with paper towels.",
      "Rub the chicken with olive oil and season generously with salt and pepper.",
      "Stuff the cavity of the chicken with lemon wedges, garlic cloves, and fresh herbs.",
      "Tie the legs together with kitchen twine and tuck the wings under the body.",
      "Place the chicken in a roasting pan and roast in the preheated oven for 1.5 to 2 hours, or until the internal temperature reaches 165°F (75°C).",
      "Let the chicken rest for 10-15 minutes before carving.",
      "Serve hot with roasted vegetables or your favorite sides.",
    ],
    nutritional_information: {
      calories: 300,
      fat: 15,
      carbohydrates: 0,
      protein: 40,
    },
  },
  {
    id: 12,
    name: "Tiramisu",
    img: "https://www.earthmarkets.com.au/wp-content/uploads/2017/12/1tiramisu.jpg",
    cuisine: "Italian",
    ingredients: [
      "ladyfinger cookies",
      "espresso coffee",
      "Marsala wine (optional)",
      "egg yolks",
      "sugar",
      "mascarpone cheese",
      "whipping cream",
      "cocoa powder",
    ],
    instructions: [
      "Brew espresso coffee and let it cool. Stir in Marsala wine if using.",
      "In a large bowl, beat egg yolks and sugar until thick and pale.",
      "Add mascarpone cheese to the egg mixture and beat until smooth.",
      "In a separate bowl, whip whipping cream until stiff peaks form.",
      "Gently fold whipped cream into the mascarpone mixture until well combined.",
      "Dip ladyfinger cookies into the espresso mixture briefly, then arrange them in a single layer in the bottom of a serving dish.",
      "Spread half of the mascarpone mixture over the cookies.",
      "Repeat with another layer of dipped cookies and remaining mascarpone mixture.",
      "Cover and refrigerate tiramisu for at least 4 hours or overnight.",
      "Before serving, dust the top of the tiramisu with cocoa powder.",
      "Serve chilled and enjoy!",
    ],
    nutritional_information: {
      calories: 350,
      fat: 25,
      carbohydrates: 25,
      protein: 5,
    },
  },
  {
    id: 13,
    name: "Shrimp Scampi",
    img: "https://theblondcook.com/wp-content/uploads/2020/06/easy-shrimp-scampi-2-3.jpg",
    cuisine: "Italian",
    ingredients: [
      "shrimp",
      "linguine",
      "butter",
      "olive oil",
      "garlic",
      "white wine",
      "lemon juice",
      "red pepper flakes",
      "parsley",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Cook linguine according to package instructions until al dente.",
      "In a large skillet, melt butter with olive oil over medium heat.",
      "Add minced garlic and red pepper flakes to the skillet, and cook until garlic is fragrant.",
      "Add shrimp to the skillet and cook until pink and opaque.",
      "Deglaze the skillet with white wine and lemon juice, and let simmer until slightly reduced.",
      "Season with salt and black pepper to taste, then toss in cooked linguine.",
      "Garnish with chopped parsley and serve hot.",
    ],
    nutritional_information: {
      calories: 400,
      fat: 15,
      carbohydrates: 40,
      protein: 25,
    },
  },
  {
    id: 14,
    name: "Beef Stroganoff",
    img: "https://www.thespruceeats.com/thmb/xFCEaU2ci3DijbovW6b919B6Dks=/4500x3000/filters:no_upscale():max_bytes(150000):strip_icc()/classic-beef-stroganoff-3051443-Final-5bacdeb4c9e77c0025142dc9.jpg",
    cuisine: "Russian",
    ingredients: [
      "beef sirloin",
      "onion",
      "mushrooms",
      "beef broth",
      "sour cream",
      "Dijon mustard",
      "flour",
      "butter",
      "egg noodles",
      "parsley",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Cook egg noodles according to package instructions until al dente.",
      "Slice beef sirloin into thin strips and season with salt and black pepper.",
      "In a large skillet, melt butter over medium heat and cook beef strips until browned. Remove and set aside.",
      "In the same skillet, sauté diced onion and sliced mushrooms until tender.",
      "Sprinkle flour over the vegetables and cook for a minute, then slowly add beef broth while stirring.",
      "Stir in sour cream and Dijon mustard until well combined.",
      "Return beef strips to the skillet and let simmer until the sauce thickens.",
      "Serve hot over cooked egg noodles, garnished with chopped parsley.",
    ],
    nutritional_information: {
      calories: 450,
      fat: 20,
      carbohydrates: 30,
      protein: 35,
    },
  },
  {
    id: 15,
    name: "Ratatouille",
    img: "https://1.bp.blogspot.com/-i1YPcdES0Jc/UT3Nwh9IJ1I/AAAAAAAABUc/R_PXP1hV97o/s1600/Ratatouille.jpg",
    cuisine: "French",
    ingredients: [
      "eggplant",
      "zucchini",
      "bell peppers",
      "onion",
      "garlic",
      "tomatoes",
      "olive oil",
      "fresh basil",
      "fresh thyme",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Slice eggplant, zucchini, and bell peppers into thin rounds.",
      "Dice onion and mince garlic.",
      "Spread diced tomatoes in the bottom of a baking dish.",
      "Arrange sliced vegetables in alternating layers on top of the tomatoes.",
      "Drizzle olive oil over the vegetables and season with salt, black pepper, fresh basil, and thyme.",
      "Cover the baking dish with aluminum foil and bake for 45-50 minutes, or until vegetables are tender.",
      "Remove foil and bake for an additional 10-15 minutes to brown the top.",
      "Serve hot as a side dish or as a main course.",
    ],
    nutritional_information: {
      calories: 200,
      fat: 10,
      carbohydrates: 25,
      protein: 5,
    },
  },

  {
    id: 17,
    name: "Chocolate Lava Cake",
    img: "https://www.savoryandsweetfood.com/wp-content/uploads/2014/02/20140227-154017.jpg",
    cuisine: "International",
    ingredients: [
      "semi-sweet chocolate",
      "butter",
      "eggs",
      "sugar",
      "vanilla extract",
      "all-purpose flour",
      "salt",
      "powdered sugar (for garnish)",
      "whipped cream or vanilla ice cream (optional, for serving)",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Grease and lightly flour individual ramekins or muffin tins.",
      "In a microwave-safe bowl, melt chocolate and butter together, stirring until smooth.",
      "In a separate bowl, beat eggs, sugar, and vanilla extract until pale and fluffy.",
      "Fold melted chocolate mixture into the egg mixture until well combined.",
      "Sift in flour and salt, gently folding until no streaks remain.",
      "Pour batter into prepared ramekins or muffin tins, filling each about 2/3 full.",
      "Bake in the preheated oven for 12-14 minutes, or until the edges are set but the center is still soft.",
      "Remove from oven and let cool for 1-2 minutes.",
      "Carefully invert each cake onto a plate, dust with powdered sugar, and serve immediately with whipped cream or vanilla ice cream.",
    ],
    nutritional_information: {
      calories: 350,
      fat: 20,
      carbohydrates: 35,
      protein: 5,
    },
  },
  {
    id: 18,
    name: "Sushi Rolls",
    img: "https://www.thespruceeats.com/thmb/IyxiJdbwFaixy4iolNYTLjBmW_w=/4288x2848/filters:fill(auto,1)/kimbap-korean-sushi-rolls-2118795-Hero-5b7dbdd346e0fb00250718b8.jpg",
    cuisine: "Japanese",
    ingredients: [
      "sushi rice",
      "nori (seaweed sheets)",
      "assorted fillings (e.g., fish, avocado, cucumber, crab meat)",
      "rice vinegar",
      "sugar",
      "salt",
      "soy sauce",
      "wasabi",
      "pickled ginger",
    ],
    instructions: [
      "Cook sushi rice according to package instructions.",
      "In a small bowl, mix rice vinegar, sugar, and salt until dissolved. Fold this mixture into the cooked rice to make sushi rice.",
      "Place a sheet of nori on a bamboo sushi mat, shiny side down.",
      "Spread a thin layer of sushi rice over the nori, leaving a small border along the edges.",
      "Arrange your choice of fillings horizontally along the lower third of the rice.",
      "Roll the sushi tightly using the bamboo mat, applying gentle pressure as you roll.",
      "Slice the sushi roll into bite-sized pieces using a sharp knife.",
      "Serve with soy sauce, wasabi, and pickled ginger.",
    ],
    nutritional_information: {
      calories: 250,
      fat: 5,
      carbohydrates: 50,
      protein: 5,
    },
  },
  {
    id: 19,
    name: "Mango Sticky Rice",
    img: "https://tasteofmissions.com/wp-content/uploads/2021/07/sticky-rice.jpeg",
    cuisine: "Thai",
    ingredients: [
      "sticky rice (glutinous rice)",
      "ripe mangoes",
      "coconut milk",
      "sugar",
      "salt",
      "toasted sesame seeds (optional)",
    ],
    instructions: [
      "Soak sticky rice in water for at least 4 hours or overnight.",
      "Steam the soaked rice until cooked and tender.",
      "In a saucepan, heat coconut milk with sugar and salt until sugar is dissolved.",
      "Remove the saucepan from heat and let the coconut milk mixture cool slightly.",
      "Peel and slice ripe mangoes.",
      "Serve the cooked sticky rice with sliced mangoes, drizzled with sweetened coconut milk.",
      "Optionally, sprinkle toasted sesame seeds over the top for added flavor and texture.",
    ],
    nutritional_information: {
      calories: 300,
      fat: 10,
      carbohydrates: 50,
      protein: 3,
    },
  },
  {
    id: 20,
    name: "Caprese Salad",
    img: "https://www.tasteofhome.com/wp-content/uploads/2018/01/Caprese-Salad_EXPS_FT20_50347_F_0610_1_home-2.jpg",
    cuisine: "Italian",
    ingredients: [
      "ripe tomatoes",
      "fresh mozzarella cheese",
      "fresh basil leaves",
      "extra virgin olive oil",
      "balsamic glaze (or balsamic vinegar)",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Slice tomatoes and fresh mozzarella cheese into uniform slices.",
      "Arrange alternating slices of tomato, mozzarella, and fresh basil leaves on a serving platter.",
      "Drizzle extra virgin olive oil and balsamic glaze (or vinegar) over the top.",
      "Season with salt and black pepper to taste.",
      "Serve immediately as a refreshing appetizer or side dish.",
    ],
    nutritional_information: {
      calories: 200,
      fat: 15,
      carbohydrates: 5,
      protein: 10,
    },
  },
];

module.exports = { recipes };
